### PR TITLE
Open the terminal when clicking Open & Start

### PR DESCRIPTION
**Pull request by BobbyMcWho**
re: my comment in #20, this would be awesome, and make the workflow quicker

### CODE REVIEW

**Comment by masliu** [comment]
This is a good suggestion, thanks. I was kind of spoiled by how some languages provided automatic running of tests so I forgot that others still had to run them. Maybe we can hide this behind a setting for people who don't need to open the terminal?

**Comment by BobbyMcWho** [comment]
@masliu we could do that, I didn't want to complicate it too much re: settings, but I can take a look

**Comment by BobbyMcWho** [comment]
@masliu 2da3e09 should take care of your concerns

**Comment by masliu** [comment]
That's great, thanks.

**Pull request merged**
